export const products = [
  {
      id: 101,
      name: "Chocolate Fudge Cake",
      image: require("../assets/chocolate-fudge.jpg"),
      price: 20,
      subcategory: "Adult Cakes",
      description: "Rich chocolate cake with a fudgy texture.",
      categoryId: 1,
  },
  {
      id: 102,
      name: "Vanilla Funfetti Cake",
      image: require("../assets/vanilla-funfetti.jpg"),
      price: 18,
      subcategory: "Kids' Cakes",
      description: "Vanilla cake with colorful sprinkles.",
      categoryId: 1,
  },
  {
      id: 103,
      name: "Vanilla Rose Cake",
      image: require("../assets/vanilla-rose.jpg"),
      price: 30,
      subcategory: "Elegant Cakes",
      description: "Delicate vanilla cake with rose decorations.",
      categoryId: 2,
  },
  {
      id: 104,
      name: "Red Velvet Cake",
      image: require("../assets/red-velvet.jpg"),
      price: 25,
      subcategory: "Traditional Cakes",
      description: "Classic red velvet cake with cream cheese frosting.",
      categoryId: 2,
  },
  {
      id: 105,
      name: "Chocolate Cupcake",
      image: require("../assets/chocolate-cupcake.jpg"),
      price: 5,
      subcategory: "Cupcakes",
      description: "Mini chocolate cake topped with frosting.",
      categoryId: 3,
  },
  {
      id: 106,
      name: "Strawberry Mousse",
      image: require("../assets/strawberry-mousse.jpg"),
      price: 7,
      subcategory: "Mousses",
      description: "Creamy strawberry mousse dessert.",
      categoryId: 3,
  },
  {
      id: 107,
      name: "Butter Croissant",
      image: require("../assets/butter-croissant.jpg"),
      price: 3,
      subcategory: "Pastries",
      description: "Flaky, buttery croissant baked to perfection.",
      categoryId: 3,
  },
];
